name: 'samurai'
version: 0.0.1
description: >
  An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  http_server: ">=0.9.0 <0.10.0"
  http: ">=0.9.0 <0.10.0"
  route: ">=0.4.0 <0.5.0"
  logging: ">=0.9.0 <0.10.0"
